apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: zookeeper
  namespace: presidential-paradise
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: zookeeper
  data:
  - secretKey: DISCORD_APP_ID
    remoteRef:
      key: k8s/presidential-paradise/zookeeper
      property: discord_app_id
  - secretKey: DISCORD_PUBLIC_KEY
    remoteRef:
      key: k8s/presidential-paradise/zookeeper
      property: discord_public_key
  - secretKey: DISCORD_TOKEN
    remoteRef:
      key: k8s/presidential-paradise/zookeeper
      property: discord_token
  - secretKey: TWITTER_TOKEN
    remoteRef:
      key: k8s/presidential-paradise/zookeeper
      property: twitter_token
